### ISSUE TITLE
Docker run fails at WebUI creation

### ISSUE THREAD

**Issue by ventu** [l1na-forever/stable-diffusion-rocm-docker#28]
I am encountering an issue with running Stable Diffusion through docker. This is running on a RX580 on a HP MicroServer. This is the result of the run command.

`
sudo docker run -e HSA_OVERRIDE_GFX_VERSION=10.3.0 -it --network=host --device=/dev/kfd --device=/dev/dri --group-add=video --ipc=host --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v $(pwd):/pwd --name stable-diffusionv2  l1naforever/stable-diffusion-rocm:latest

Python 3.7.13 (default, Mar 29 2022, 02:18:16) 
[GCC 7.5.0]
Commit hash: 08b3f7aef15f74f4d2254b1274dd66fcc7940348
Installing gfpgan
Installing clip
Cloning Stable Diffusion into repositories/stable-diffusion...
Cloning Taming Transformers into repositories/taming-transformers...
Cloning K-diffusion into repositories/k-diffusion...
Cloning CodeFormer into repositories/CodeFormer...
Cloning BLIP into repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
Traceback (most recent call last):
  File "launch.py", line 168, in <module>
    prepare_enviroment()
  File "launch.py", line 152, in prepare_enviroment
    run_pip(f"install -r {requirements_file}", "requirements for Web UI")
  File "launch.py", line 60, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "launch.py", line 32, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Web UI.
Command: "/opt/conda/bin/python" -m pip install -r requirements.txt --prefer-binary
Error code: 1
stdout: Requirement already satisfied: basicsr in /opt/conda/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.4.2)
Collecting diffusers
  Downloading diffusers-0.21.4-py3-none-any.whl (1.5 MB)
Collecting fairscale==0.4.4
  Downloading fairscale-0.4.4.tar.gz (235 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting fonts
  Downloading fonts-0.0.3-py3-none-any.whl (4.2 kB)
Collecting font-roboto
  Downloading font-roboto-0.0.1.tar.gz (2.4 MB)
Requirement already satisfied: gfpgan in /opt/conda/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (1.3.5)
Collecting gradio==3.4.1
  Downloading gradio-3.4.1-py3-none-any.whl (5.3 MB)
Collecting invisible-watermark
  Downloading invisible_watermark-0.2.0-py3-none-any.whl (1.6 MB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (1.18.5)
Collecting omegaconf
  Downloading omegaconf-2.3.0-py3-none-any.whl (79 kB)
Collecting piexif
  Downloading piexif-1.1.3-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: Pillow in /opt/conda/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (9.2.0)
Collecting pytorch_lightning
  Downloading pytorch_lightning-1.9.5-py3-none-any.whl (829 kB)
Collecting realesrgan
  Downloading realesrgan-0.3.0-py3-none-any.whl (26 kB)
Requirement already satisfied: scikit-image>=0.19 in /opt/conda/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (0.19.3)
Collecting timm==0.4.12
  Downloading timm-0.4.12-py3-none-any.whl (376 kB)
Collecting transformers==4.19.2
  Downloading transformers-4.19.2-py3-none-any.whl (4.2 MB)
Requirement already satisfied: torch in /opt/conda/lib/python3.7/site-packages (from -r requirements.txt (line 18)) (1.13.0a0+gitd566718)
Collecting einops
  Downloading einops-0.6.1-py3-none-any.whl (42 kB)
Collecting jsonmerge
  Downloading jsonmerge-1.9.2-py3-none-any.whl (19 kB)
Collecting clean-fid
  Downloading clean_fid-0.1.35-py3-none-any.whl (26 kB)
Collecting resize-right
  Downloading resize_right-0.0.2-py3-none-any.whl (8.9 kB)
Collecting torchdiffeq
  Downloading torchdiffeq-0.2.4-py3-none-any.whl (32 kB)
Collecting kornia
  Downloading kornia-0.6.12-py2.py3-none-any.whl (653 kB)
Collecting lark
  Downloading lark-1.1.9-py3-none-any.whl (111 kB)
Requirement already satisfied: scipy in /opt/conda/lib/python3.7/site-packages (from basicsr->-r requirements.txt (line 1)) (1.6.3)
Requirement already satisfied: tb-nightly in /opt/conda/lib/python3.7/site-packages (from basicsr->-r requirements.txt (line 1)) (2.11.0a20221005)
Requirement already satisfied: opencv-python in /opt/conda/lib/python3.7/site-packages (from basicsr->-r requirements.txt (line 1)) (4.10.0.84)
Requirement already satisfied: future in /opt/conda/lib/python3.7/site-packages (from basicsr->-r requirements.txt (line 1)) (0.18.2)
Requirement already satisfied: torchvision in /opt/conda/lib/python3.7/site-packages/torchvision-0.14.0a0+369317f-py3.7-linux-x86_64.egg (from basicsr->-r requirements.txt (line 1)) (0.14.0a0+369317f)
Requirement already satisfied: yapf in /opt/conda/lib/python3.7/site-packages (from basicsr->-r requirements.txt (line 1)) (0.40.2)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.7/site-packages (from basicsr->-r requirements.txt (line 1)) (6.0)
Requirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from basicsr->-r requirements.txt (line 1)) (2.27.1)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.7/site-packages (from basicsr->-r requirements.txt (line 1)) (4.63.0)
Requirement already satisfied: lmdb in /opt/conda/lib/python3.7/site-packages (from basicsr->-r requirements.txt (line 1)) (1.5.1)
Requirement already satisfied: addict in /opt/conda/lib/python3.7/site-packages (from basicsr->-r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.7/site-packages (from diffusers->-r requirements.txt (line 2)) (3.12.2)
Requirement already satisfied: importlib-metadata in /opt/conda/lib/python3.7/site-packages (from diffusers->-r requirements.txt (line 2)) (6.7.0)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.7/site-packages (from diffusers->-r requirements.txt (line 2)) (2024.4.16)
Collecting huggingface-hub>=0.13.2
  Downloading huggingface_hub-0.16.4-py3-none-any.whl (268 kB)
Collecting safetensors>=0.3.1
  Downloading safetensors-0.4.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (436 kB)
Requirement already satisfied: facexlib>=0.2.5 in /opt/conda/lib/python3.7/site-packages (from gfpgan->-r requirements.txt (line 6)) (0.3.0)
Collecting httpx
  Downloading httpx-0.24.1-py3-none-any.whl (75 kB)
Collecting pydub
  Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Collecting orjson
  Downloading orjson-3.9.7-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (138 kB)
Collecting paramiko
  Downloading paramiko-3.5.0-py3-none-any.whl (227 kB)
Collecting ffmpy
  Downloading ffmpy-0.3.3-py3-none-any.whl (5.8 kB)

stderr: ERROR: Package 'ffmpy' requires a different Python: 3.7.13 not in '>=3.8.1,<4.0.0'
WARNING: You are using pip version 20.1.1; however, version 24.0 is available.
You should consider upgrading via the '/opt/conda/bin/python -m pip install --upgrade pip' command.
`

**Comment by qgjdev** [comment]
Any solution on that?
