### ISSUE TITLE
CodeFormer/PyTorch issue

### ISSUE THREAD

**Issue by dlasher** [l1na-forever/stable-diffusion-rocm-docker#9]
Docker on Ubuntu 22LTS - AMD 6900XT GPU

Fresh pull today, fails to start, complaining about setting up CodeFormer. tore down, re-pulled from scratch, same error:

`
Error setting up CodeFormer:
Traceback (most recent call last):
  File "/sd/modules/codeformer_model.py", line 38, in setup_model
    from facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/sd/repositories/CodeFormer/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from facelib.detection import init_detection_model
  File "/sd/repositories/CodeFormer/facelib/detection/__init__.py", line 11, in <module>
    from .yolov5face.face_detector import YoloDetector
  File "/sd/repositories/CodeFormer/facelib/detection/yolov5face/face_detector.py", line 20, in <module>
    IS_HIGH_VERSION = tuple(map(int, torch.__version__.split('+')[0].split('.'))) >= (1, 9, 0)
ValueError: invalid literal for int() with base 10: '0a0'

WARNING:root:Pytorch pre-release version 1.13.0a0+gitd566718 - assuming intent to test it
Traceback (most recent call last):
  File "launch.py", line 169, in <module>
    start_webui()
  File "launch.py", line 164, in start_webui
    webui.webui()
  File "/sd/webui.py", line 92, in webui
    initialize()
  File "/sd/webui.py", line 85, in initialize
    shared.sd_model = modules.sd_models.load_model()
  File "/sd/modules/sd_models.py", line 181, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "/sd/repositories/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/sd/repositories/stable-diffusion/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/sd/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 19, in <module>
    from pytorch_lightning.utilities.distributed import rank_zero_only
ImportError: cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed' (/opt/conda/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py)
`

**Comment by dlasher** [comment]
Just to confirm - fresh Ubuntu 22 install on empty drive, installed docker, and pulled [stable-diffusion-rocm-docker] - errors out the same way. Something new is broken in the last 2 weeks (since I set this up the last time)

**Comment by Fecfec97** [comment]
To add, I am also experiencing this error on Manjaro. I haven't had this git working as of yet as I have only tried to install it today. 

I have managed to get past this point with a standard installation before.

**Comment by FinnRG** [comment]
The specific error was fixed in https://github.com/sczhou/CodeFormer/commit/8e5f81be41f283942b4346fef87ca1fad2cb889d, but I couldn't find the reason, why this container still pulls the old version
